# fly.toml app configuration file generated for booktowerbot on 2026-09-03T13:57:18Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'booktowerbot'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256

[mounts]
  source = "booktower_data"
  destination = "/app/assets"
  initial_size = "1gb"